CREATE TABLE `Company` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`Name` varchar(255) NOT NULL,
`Email` varchar(255) NOT NULL,
`Phone` varchar(255) NOT NULL,
`Address` varchar(255) NOT NULL,
PRIMARY KEY (`ID`));

CREATE TABLE `Survey` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`CID` int(11) NOT NULL,
`Date` date NOT NULL,
PRIMARY KEY (`ID`),
KEY `FOREIGN` (`CID`),
CONSTRAINT `Survey_ibfk_1` FOREIGN KEY (`CID`) REFERENCE
`Company` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `Department` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`SID` int(11) NOT NULL,
`Name` varchar(255) NOT NULL,
PRIMARY KEY (`ID`),
KEY `FOREIGN` (`SID`),
CONSTRAINT `Department_ibfk_1` FOREIGN KEY (`SID`) REFERENCES `Survey` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `Participant` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`DID` int(11) NOT NULL,
`Email` varchar(255) NOT NULL,
`Submitted` int(1) NOT NULL,
PRIMARY KEY (`ID`),
KEY `FOREIGN` (`DID`),
CONSTRAINT `Participant_ibfk_1` FOREIGN KEY (`DID`) REFERENCES `Department` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `Question` (
`ID` int(11) NOT NULL,
`QL` varchar(255) NOT NULL,
`QR` varchar(255) NOT NULL,
PRIMARY KEY (`ID`));

CREATE TABLE `Response` (
`ID` int(11) NOT NULL AUTO_INCREMENT,
`DID` int(11) NOT NULL,
`QID` int(11) NOT NULL,
`Response` tinyint(11) NOT NULL,
PRIMARY KEY (`ID`),
KEY `FOREIGN1` (`QID`),
KEY `FOREIGN2` (`DID`),
CONSTRAINT `Response_ibfk_1` FOREIGN KEY (`DID`) REFERENCES `Department` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `Response_ibfk_2` FOREIGN KEY (`QID`) REFERENCES `Question` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `SurveyQuestion` (
`SID` int(11) NOT NULL,
`QID` int(11) NOT NULL,
PRIMARY KEY (`SID`,`QID`),
KEY `FOREIGN1` (`SID`),
KEY `FOREIGN2` (`QID`),
CONSTRAINT `SurveyQuestion_ibfk_2` FOREIGN KEY (`QID`) REFERENCES `Question` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `SurveyQuestion_ibfk_1` FOREIGN KEY (`SID`) REFERENCES `Survey` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE);